version: '3.8'

services:
  fastapi-service:
    build: ./fastapi-service
    ports:
      - "6000:6000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  nestjs-service:
    build: ./nestjs-service
    ports:
      - "4000:4000"
    depends_on:
      - fastapi-service
    networks:
      - app-network

  frontend:
    build: ./frontend-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge